#!/usr/bin/env bash


if [ "$1" == "" ]; then
  export COFFEA_IMAGE=coffeateam/coffea-dask-cc7:latest
else
  export COFFEA_IMAGE=$1
fi

grep -v '^include' /etc/condor/config.d/00hep_wisc.config > .condor_config

EXTERNAL_BIND=${PWD} singularity exec -B ${PWD}:/srv -B /etc/condor -B /scratch -B /afs --pwd /srv \
  /cvmfs/unpacked.cern.ch/registry.hub.docker.com/${COFFEA_IMAGE} \
  /bin/bash --rcfile /srv/.bashrc
